name: 'Continuous Integration'
on: [push]
jobs:
  afterPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn
      - name: prettier
        run: yarn prettier
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
